version: "3.9"

networks:
  grafana:

volumes:
  app_data: { }

services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    networks:
      - grafana

  grafana:
    image: grafana/grafana:8.4.5
    ports:
      - 3000:3000
    networks:
      - grafana
